import { describe, expect, it } from 'vitest';
import { parseYarnLockfile } from './yarn-lockfile.js';

const V1_LOCKFILE = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@scope/bar@^4.0.0", "@scope/bar@^4.5.0":
  version "4.5.6"
  resolved "https://registry.yarnpkg.com/@scope/bar/-/bar-4.5.6.tgz#aaa"
  integrity sha512-aaa
  dependencies:
    foo "^1.0.0"

foo@^1.0.0:
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/foo/-/foo-1.2.3.tgz#bbb"
  integrity sha512-bbb
`;

const BERRY_LOCKFILE = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"@scope/bar@npm:^4.0.0":
  version: 4.5.6
  resolution: "@scope/bar@npm:4.5.6"
  checksum: 10c0/aaa
  languageName: node
  linkType: hard

"foo@npm:^1.0.0, foo@npm:^1.2.0":
  version: 1.2.3
  resolution: "foo@npm:1.2.3"
  checksum: 10c0/bbb
  languageName: node
  linkType: hard
`;

describe('parseYarnLockfile', () => {
  it('extracts package versions from a classic v1 lockfile', () => {
    const versions = parseYarnLockfile(V1_LOCKFILE);

    expect(versions?.get('@scope/bar')).toBe('4.5.6');
    expect(versions?.get('foo')).toBe('1.2.3');
    expect(versions?.size).toBe(2);
  });

  it('extracts package versions from a berry lockfile and ignores __metadata', () => {
    const versions = parseYarnLockfile(BERRY_LOCKFILE);

    expect(versions?.get('@scope/bar')).toBe('4.5.6');
    expect(versions?.get('foo')).toBe('1.2.3');
    expect(versions?.has('__metadata')).toBe(false);
    expect(versions?.size).toBe(2);
  });

  it('returns undefined when no package blocks are present', () => {
    expect(parseYarnLockfile('')).toBeUndefined();
    expect(parseYarnLockfile('# yarn lockfile v1\n')).toBeUndefined();
    expect(parseYarnLockfile('not a lockfile')).toBeUndefined();
  });

  it('ignores selectors without a version separator', () => {
    const content = 'justaname:\n  version "1.0.0"\n\nfoo@^1.0.0:\n  version "2.0.0"\n';
    const versions = parseYarnLockfile(content);

    expect(versions?.size).toBe(1);
    expect(versions?.get('foo')).toBe('2.0.0');
  });
});
